[GLOBAL]
pants_version = "2.18.0"
pythonpath = ["pants-plugins"]
print_stacktrace = true

backend_packages = [
    "pants.backend.plugin_development",
    "pants.backend.python",
    "pants.backend.python.lint.bandit",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.pylint",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.pyupgrade",
    "pants.backend.shell",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.shell.lint.shfmt",
    "experimental.julia",
]

[source]
root_patterns = [
    "examples",
    "pants-plugins",
]

[python]
interpreter_constraints = [">=3.9,<3.11"]

[bandit]
args = ["--skip B101"]

[flake8]
args = ["--max-line-length 88", "--ignore=E501"]

[isort]
args = "--profile black"

[pylint]
# Skipping documentation warnings, and f-string log warnings
args = "--disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,logging-fstring-interpolation"

[pyupgrade]
args = "--py39-plus"

[shfmt]
# See https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd#printer-flags.
args = ["-i 4", "-ci", "-sr"]

[anonymous-telemetry]
enabled = false
